### ISSUE TITLE
Unable to find ibidn-1.15.tar.gz

### ISSUE THREAD

**Issue by chathura2** [funkyboy/Building-a-Jabber-client-for-iOS#3]
During compiling unable to find Building-a-Jabber-client-for-iOS-master/xmpp/Vendor/libidn/libidn-1.15.tar.gz: No such file or directory.  Please include this in this public zip download.

**Comment by ferrakkem** [comment]
Building-a-Jabber-client-for-iOS-master/xmpp/Vendor/libidn/libidn-1.15.tar.gz: No such file or directory

where i get this file

**Comment by funkyboy** [comment]
This is a very old project and I can't provide any kind of support at the moment. @ferrakkem
