### ISSUE TITLE
Code doesn't seem to contain XMPP Classes

### ISSUE THREAD

**Issue by rptwsthi** [funkyboy/Building-a-Jabber-client-for-iOS#9]
I have downloaded the code and trying to execute it. But it comes with error.

<b>error: /Users/developer/Work/iOS/Projects/Demo And Support/Building-a-Jabber-client-for-iOS-master/xmpp/Vendor/libidn/libidn-1.15.tar.gz: No such file or directory</b>

Also it doesn't seem to contain, xmpp files. See attached image.
![screen shot 2015-01-10 at 17 19 16](https://cloud.githubusercontent.com/assets/1061288/5691452/ed5964ca-98ec-11e4-826b-1eb0bae2d45b.png)

**Comment by funkyboy** [comment]
Yup, I am aware of that plus many other issues. Unfortunately I can't provide any support at the moment.
